### ISSUE TITLE
BUG: SingBox Version Not Correct and not updated

### ISSUE THREAD

**Issue by famirHossein81** [Mahdi-zarei/nekoray#7] opened 2024-05-12 09:37 UTC
## Describe the problem
First Thanks for your effort and time you devoted to this project. In the last Verstion the sing-box core- as you said- should be 1.9.15 but it is still 1.9.14. I have checked the nekobox-core to make sure that it is not a misspelling in the application. But it was 1.9.14 still.
Expected behavior:

Actual behavior:

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by Mahdi-zarei** [comment] 2024-05-12 13:49
This is a visual bug, the version printed is a hard-coded value in the sing-box-extra files and while the sing-box version is updated to 1.9.15, I forgot to update the version value in the files.
duplicate of #5

**Closed by Mahdi-zarei** 2024-05-12 13:49 UTC
Labels: duplicate

**Comment by famirHossein81** [comment] 2024-05-12 16:17
hmm. Understood. Again Thanks for Everything you done.
