### ISSUE TITLE
BUG: NekoRay crashes on M2 Pro Mac

### ISSUE THREAD

**Issue by Werameli** [Mahdi-zarei/nekoray#127] opened 2024-08-30 21:20 UTC
## Describe the problem

Expected behavior: program launch normally

Actual behavior: Program crashes

## How to reproduce

Download arm64 build of NekoRay.
Try to bypass "app is damaged" by xattr 
Get an unxecpected exit

## log

https://pastebin.com/6dGU6wpA

**Comment by Mahdi-zarei** [comment] 2024-08-31 01:56
I am not familiar with macOS development, but from what I can see it seems the problem is caused by the nekoray app not being signed. Could you try to set nekoray as an exception to the security checks and see if works?

**Comment by Werameli** [comment] 2024-08-31 09:31
@Mahdi-zarei 

I just can't do it because nekoray don't even show up on privacy tab in settings

**Comment by Mahdi-zarei** [comment] 2024-08-31 09:58
> @Mahdi-zarei
> 
> I just can't do it because nekoray don't even show up on privacy tab in settings

This is a bit troublesome, I do not have a mac environment to work on this myself, and the mac release build process has not been changed recently. Does anyone else who uses Mac have had this issue? It will be great if you could share how you solved this problem.

**Comment by Werameli** [comment] 2024-08-31 10:20
> > @Mahdi-zarei
> > I just can't do it because nekoray don't even show up on privacy tab in settings
> 
> This is a bit troublesome, I do not have a mac environment to work on this myself, and the mac release build process has not been changed recently. Does anyone else who uses Mac have had this issue? It will be great if you could share how you solved this problem.


I did some research and found 2 issues related to same problem as mine, you should check it

https://github.com/dotnet/maui/issues/12483
https://github.com/dotnet/maui/issues/11830

Maybe it will help to determine a solution

**Comment by Mahdi-zarei** [comment] 2024-08-31 10:51
There are some stuff there that could help us out, I will try them when I get some free time. Will appreciate it if you oculd test them once they are available.

**Comment by Werameli** [comment] 2024-08-31 21:27
> There are some stuff there that could help us out, I will try them when I get some free time. Will appreciate it if you oculd test them once they are available.

Sure I'll test if I'll be available when you fix macOS build

**Comment by Mahdi-zarei** [comment] 2024-08-31 22:26
I tried removing the part which was providing an invalid signature, it's a shot in the dark, but could you see if it works now?
https://github.com/Mahdi-zarei/nekoray/actions/runs/10648659092
you can download the built file from the link above.

**Comment by Werameli** [comment] 2024-09-01 10:34
> I tried removing the part which was providing an invalid signature, it's a shot in the dark, but could you see if it works now? https://github.com/Mahdi-zarei/nekoray/actions/runs/10648659092 you can download the built file from the link above.

Which one do I need to test? 
1. build-go (arm64 derwin)
2. build-cpp (arm64 macOS 14)

**Comment by Mahdi-zarei** [comment] 2024-09-01 10:37
> > I tried removing the part which was providing an invalid signature, it's a shot in the dark, but could you see if it works now? https://github.com/Mahdi-zarei/nekoray/actions/runs/10648659092 you can download the built file from the link above.
> 
> Which one do I need to test?
> 
>     1. build-go (arm64 darwin)
> 
>     2. build-cpp (arm64 macOS 14)

The second one, the first one is only the nekobox core.

**Comment by Werameli** [comment] 2024-09-01 10:51
> > > I tried removing the part which was providing an invalid signature, it's a shot in the dark, but could you see if it works now? https://github.com/Mahdi-zarei/nekoray/actions/runs/10648659092 you can download the built file from the link above.
> > 
> > 
> > Which one do I need to test?
> > ```
> > 1. build-go (arm64 darwin)
> > 
> > 2. build-cpp (arm64 macOS 14)
> > ```
> 
> The second one, the first one is only the nekobox core.


Unfortunately, this build still gives the same error

**Comment by Werameli** [comment] 2024-09-01 11:03
@Mahdi-zarei 

https://stackoverflow.com/questions/70451363/exception-type-exc-crash-sigkill-code-signature-invalid-only-after-enabling

I found a guy with the same problem as mine. Take a look at it maybe it will help.

**Comment by Mahdi-zarei** [comment] 2024-09-01 11:32
> @Mahdi-zarei
> 
> https://stackoverflow.com/questions/70451363/exception-type-exc-crash-sigkill-code-signature-invalid-only-after-enabling
> 
> I found a guy with the same problem as mine. Take a look at it maybe it will help.

Tried the codesign solution, here are the build files:
https://github.com/Mahdi-zarei/nekoray/actions/runs/10653585079

Can you please see if it has helped?

**Comment by Werameli** [comment] 2024-09-01 11:38
> > @Mahdi-zarei
> > https://stackoverflow.com/questions/70451363/exception-type-exc-crash-sigkill-code-signature-invalid-only-after-enabling
> > I found a guy with the same problem as mine. Take a look at it maybe it will help.
> 
> Tried the codesign solution, here are the build files: https://github.com/Mahdi-zarei/nekoray/actions/runs/10653585079
> 
> Can you please see if it has helped?

Bingo! That build is working
![image](https://github.com/user-attachments/assets/19a98a45-a293-4f8b-b299-adf67398d6fb)

**Comment by Mahdi-zarei** [comment] 2024-09-01 11:41
> > > @Mahdi-zarei
> > > https://stackoverflow.com/questions/70451363/exception-type-exc-crash-sigkill-code-signature-invalid-only-after-enabling
> > > I found a guy with the same problem as mine. Take a look at it maybe it will help.
> > 
> > 
> > Tried the codesign solution, here are the build files: https://github.com/Mahdi-zarei/nekoray/actions/runs/10653585079
> > Can you please see if it has helped?
> 
> Bingo! That build is working! I just approved to open this app via settings ![image](https://private-user-images.githubusercontent.com/105867115/363488502-19a98a45-a293-4f8b-b299-adf67398d6fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxOTExMDIsIm5iZiI6MTcyNTE5MDgwMiwicGF0aCI6Ii8xMDU4NjcxMTUvMzYzNDg4NTAyLTE5YTk4YTQ1LWEyOTMtNGY4Yi1iMjk5LWFkZjY3Mzk4ZDZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQxMTQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGM2MGYwMTE1NWZhM2MzOGJiYTYwMTIyNGI0MTgzZTE2NzA0ODFhZjc4NDA0Y2ZmMzBiODBiOTA2MzY0MWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xG-pB-hxUcj3K6FG1fELYrHs0YNKpj567CiaE2_Pohc)

Great! Thank you for your help.
I have some other bugs to fix and then this build will be released properly as well.

**Comment by Werameli** [comment] 2024-09-01 11:42
> > > > @Mahdi-zarei
> > > > https://stackoverflow.com/questions/70451363/exception-type-exc-crash-sigkill-code-signature-invalid-only-after-enabling
> > > > I found a guy with the same problem as mine. Take a look at it maybe it will help.
> > > 
> > > 
> > > Tried the codesign solution, here are the build files: https://github.com/Mahdi-zarei/nekoray/actions/runs/10653585079
> > > Can you please see if it has helped?
> > 
> > 
> > Bingo! That build is working! I just approved to open this app via settings ![image](https://private-user-images.githubusercontent.com/105867115/363488502-19a98a45-a293-4f8b-b299-adf67398d6fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxOTExMDIsIm5iZiI6MTcyNTE5MDgwMiwicGF0aCI6Ii8xMDU4NjcxMTUvMzYzNDg4NTAyLTE5YTk4YTQ1LWEyOTMtNGY4Yi1iMjk5LWFkZjY3Mzk4ZDZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQxMTQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGM2MGYwMTE1NWZhM2MzOGJiYTYwMTIyNGI0MTgzZTE2NzA0ODFhZjc4NDA0Y2ZmMzBiODBiOTA2MzY0MWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xG-pB-hxUcj3K6FG1fELYrHs0YNKpj567CiaE2_Pohc)
> 
> Great! Thank you for your help. I have some other bugs to fix and then this build will be released properly as well.

Thank you for fixing macOS build! Will be waiting for new release :)

**Closed** 2024-09-04 14:15 UTC
Labels: help wanted
