### ISSUE TITLE
BUG: abnormal dialog width

### ISSUE THREAD

**Issue by M450ud** [Mahdi-zarei/nekoray#130] opened 2024-09-02 06:59 UTC
Adding a large number of configs to the app causes the routing editor window width to increase according to the number of configs.

**Comment by Mahdi-zarei** [comment] 2024-09-02 11:45
Please attach a screenshot or method to reproduce the problem.

**Comment by M450ud** [comment] 2024-09-02 19:32
this is the app dialog with more than 41K configs and dialog size from spy++ window.
![Screen Capture (20240902) 22-57-31](https://github.com/user-attachments/assets/1533901c-190a-43d2-aaa6-8decf9c3e1f3)

**Comment by Mahdi-zarei** [comment] 2024-09-02 23:51
This is not caused by the large number of profiles. Some of your configs have very long names and this is caused by them, however, we may still need to set a max number of characters...

**Comment by Mahdi-zarei** [comment] 2024-09-05 03:51
Fixed in 4.1.4

**Closed** 2024-09-08 10:30 UTC
Labels: insufficient information
