### ISSUE TITLE
کارنکردن کانفیگ ها

### ISSUE THREAD

**Issue by iamfarhad** [Mahdi-zarei/nekoray#103] opened 2024-08-14 18:13 UTC
سلام
بعد از اپدیت به نسخه جدید کانفیگ ها از کار افتاد و کار نمیکنه
تست هم نمیشه گرفت

**Comment by M-Sadegh-M** [comment] 2024-08-14 18:50
مجدد اپدیت کنید به ورژن 4.1.1 مشکل حل شده
اگه حل نشده دستور عمل را مطابق پست زیر دنبال کنید
https://github.com/Mahdi-zarei/nekoray/issues/102#issuecomment-2289041569

**Comment by Turbine8845** [comment] 2024-08-15 10:58
> سلام بعد از اپدیت به نسخه جدید کانفیگ ها از کار افتاد و کار نمیکنه تست هم نمیشه گرفت

I had a similar issue with version 4.1.1, where some configurations randomly stopped working, but I didn’t notice any specific patterns. Unfortunately, I accidentally updated the subscription and lost those configs. If possible, please provide more information about the configurations that are failing for you.

**Comment by Turbine8845** [comment] 2024-08-15 10:58
> مجدد اپدیت کنید به ورژن 4.1.1 مشکل حل شده اگه حل نشده دستور عمل را مطابق پست زیر دنبال کنید [#102 (comment)](https://github.com/Mahdi-zarei/nekoray/issues/102#issuecomment-2289041569)

I still have the same issues in version 4.1.1.

**Comment by M-Sadegh-M** [comment] 2024-08-15 11:34
Hello,

@Mahdi-zarei noticed that the configuration is not being generated correctly in the new version.  
He asked me to send him two configurations from the previous and current versions.  
By comparing the configurations, he identified the bug and fixed it with this [commit](https://github.com/Mahdi-zarei/nekoray/commit/982455bbc2e888b835fa1747ab6d3fcca72ce25a).

If you're having an issue too, export the non-working config with CTRL + E and send it, so he can check it.

**Comment by Mahdi-zarei** [comment] 2024-08-16 10:25
Try 4.1.2

**Comment by Turbine8845** [comment] 2024-08-17 22:22
> Try 4.1.2

The problem is fixed in version 4.1.2. I guess this issue can be closed now.

**Comment by iamfarhad** [comment] 2024-08-18 13:08
برای من همچنان کار نمیکنه

**Comment by Mahdi-zarei** [comment] 2024-08-28 20:41
Try 4.1.3

**Closed** 2024-08-31 14:01 UTC
